### ISSUE TITLE
Report an error

### ISSUE THREAD

**Issue by 2516455367** [LOBYXLYX/Cloudflare-Bypass#13]
![image](https://github.com/user-attachments/assets/c35c89e5-377e-495b-9b92-6107ee9064d5)
![image](https://github.com/user-attachments/assets/53032a15-39b3-4b71-91e0-1ff167ceed5f)

**Comment by LOBYXLYX** [comment]
This is a random error, sometimes the turnstile solver can throw errors because cloudflare does not have a static code


I will try to solve these random errors
