### ISSUE TITLE
Bypass not working

### ISSUE THREAD

**Issue by M0N0Atomic** [LOBYXLYX/Cloudflare-Bypass#19]
INPUT
```python
from aqua import CF_Solver

cf = CF_Solver('https://ascelibrary.org')
cookie = cf.cookie()
print(cookie)
response = cf.client.get(url='https://ascelibrary.org')
print("Failed" if "Just a moment" in response.text else "Success")
```

OUTPUT
```
Failed
```

I also tried with curl_cffi.requests.Session with and without Residential proxies as well.
I checked to see if it's Turnstile but didn't find anything to confirm that.

**Comment by LOBYXLYX** [comment]
I think my cf_bypass will not work with that website, it has very high protection, I tried to use TLS and it works, but sometimes you can get 403 if you send too many requests

![Screenshot_20241222_082854](https://github.com/user-attachments/assets/768e1c63-d57b-41aa-9d32-f4033dcd7a04)
![Screenshot_20241222_083143](https://github.com/user-attachments/assets/e7df603e-aa2d-48a3-972d-348cbe963e93)

https://github.com/FlorianREGAZ/Python-Tls-Client

**Comment by M0N0Atomic** [comment]
I see. Thanks for the solution. Could you tell me where was the ja3 and other parameters acquired from?

**Comment by LOBYXLYX** [comment]
You can get your ja3 here: https://scrapfly.io/web-scraping-tools/ja3-fingerprint?__tab%5Btab-alg-group%5D=alg-ja3

And in the tls_client doc there is the use of parameters
