### ISSUE TITLE
Is turnstile function working?

### ISSUE THREAD

**Issue by Gujal00** [LOBYXLYX/Cloudflare-Bypass#5]
Thanks a lot for this code, it is impressive at how fast it collects the cookies. I have tried it with a few sites with the example code and hit this one where it doesn't work. It collects the cookie but doesn't get the page after `https://extratorrent.st/`.

Can you please take a look. Thanks

**Comment by LOBYXLYX** [comment]
I haven't finished Turnstile Bypass yet.

There is little chance that I can successfully bypass turnstile, beacuse Cloudflare is very difficult to bypass if it is based on HTTP requests

**Comment by Gujal00** [comment]
Thank you for your efforts, I was not sure if extratorrent was using turnstile. You can confirm if it indeed is turnstile protected or not.
If it is indeed turnstile protected, then certainly park it until you have figured out a way.
