### ISSUE TITLE
Not Bypassing cloudflare 

### ISSUE THREAD

**Issue by 7xm-xyz** [LOBYXLYX/Cloudflare-Bypass#8]
from aqua import CF_Solver

# other
cf = CF_Solver('https://artlist.io')
cookie2 = cf.cookie()
print(cookie2)
url = 'https://artlist.io'

# follow up requests
response = cf.client.get(url=url, timeout=10)
print(response.text)

Still output is cloudflare error.

**Comment by LOBYXLYX** [comment]
Website is protected with turnstile, this works with sites that don't have turnstile

**Comment by 7xm-xyz** [comment]
can you please Guide me to have cloudflare bypass turnstile ??? like website spamzilla.io ???

**Comment by LOBYXLYX** [comment]
There are some turnstile bypasses that work, but they are based on Selenium or Playwright

**Comment by 7xm-xyz** [comment]
Actually I want to develop Proxy script . ANd If we use selenium/Playwright it will very slow as each request will open instance and get data etc

**Comment by LOBYXLYX** [comment]
If I manage to finish this turnstile bypass, it would take 15~20 seconds to bypass it, because this sends many GET requests and parses the cf code
